/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorWorkArea;

import Business.Enterprise.Enterprise;
import Business.LabTest.LabTest;
import Business.Main.EcoSystem;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.WorkQueue.DoctorRequest;
import Business.WorkQueue.OPTC_Request;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author chief_kmv
 */
public class ShowResults extends javax.swing.JPanel {

    /**
     * Creates new form ShowResults
     */
    private JPanel userProcessContainer;
    private DoctorRequest request;
    private EcoSystem business;

    public ShowResults(JPanel userProcessContainer, WorkRequest request, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = (DoctorRequest) request;
        this.business = business;
        populateFields();
    }

    public void populateFields() {
        LabTest test = request.getLabtest();
        bloodtypeTxt.setText(test.getBloodType());
        sugarTxt.setText(test.getBloodSugar());
        infectiousTxt.setText(test.getInfectiousDiseases());
        tissueTxt.setText(test.getTissueType());
        resultJTextField1.setText(test.getTestResult());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bloodtypeTxt = new javax.swing.JTextField();
        resultJTextField1 = new javax.swing.JTextField();
        infectiousTxt = new javax.swing.JTextField();
        sugarTxt = new javax.swing.JTextField();
        tissueTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        SendBtn = new javax.swing.JButton();
        organTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Result");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, 30));
        add(bloodtypeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 88, -1));
        add(resultJTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 88, -1));
        add(infectiousTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 88, -1));
        add(sugarTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 88, -1));
        add(tissueTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 88, -1));

        jLabel2.setText("Infectious Diseases");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, 20));

        jLabel3.setText("Blood Type");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        jLabel4.setText("Tissue Type");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, 20));

        jLabel5.setText("Blood Sugar");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, -1, -1));

        SendBtn.setText("Send To Registry");
        SendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendBtnActionPerformed(evt);
            }
        });
        add(SendBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 570, -1, -1));

        organTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organTxtActionPerformed(evt);
            }
        });
        add(organTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 100, -1));

        jLabel6.setText("Organ Needed");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void SendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendBtnActionPerformed
        // TODO add your handling code here:
        OPTC_Request optc_req=new OPTC_Request();
        optc_req.setPatient(request.getPatient());
        optc_req.setLabtest(request.getLabtest());
        optc_req.setSender(request.getSender());
        optc_req.setStatus("Sent to Registry");
        optc_req.setOrgan(organTxt.getText());
        if (request.getPatient().getType().equals("Reciever")) {
            for (Network network : business.getNetworkList()) {
                for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {
                   
                    if(ent.getEnterpriseType().toString().equals("Organ Procurement and Transplant Center")){
                        //System.out.println(ent.getOrganizationDirectory().getOrganizationList());
                        for(Organization org:ent.getOrganizationDirectory().getOrganizationList()){
                            org.getWorkQueue().addRequest(optc_req);
//                            System.out.println(org);
//                            System.out.println(org.getWorkQueue().getWorkRequestList().get(0));
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_SendBtnActionPerformed

    private void organTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SendBtn;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField bloodtypeTxt;
    private javax.swing.JTextField infectiousTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField organTxt;
    private javax.swing.JTextField resultJTextField1;
    private javax.swing.JTextField sugarTxt;
    private javax.swing.JTextField tissueTxt;
    // End of variables declaration//GEN-END:variables
}
